[package]
name = "algebraic-enum-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.36"
syn = {version = "2.0.66", features= [ "full", "parsing", "derive" ]}

[lib]
proc-macro = true
